### PR TITLE
Add support for simulating LDP container behaviour

### PR DESCRIPTION
**Pull request by joachimvh**
Adds examples that show how you can create a derived resource that is the same as a standard LDP container. Also includes a bunch of cleanup and refactor changes that were caused by looking into this.

After this, you can go to `http://localhost:3000` to see `ldp:contains` triples that were dynamically generated based on the metadata of other derived resources.

Currently we still have to manually define in the metadata config which containers should generate triples like that. We could potentially update it in the future so all containers that contain at least 1 derived resource do this.

Another disadvantage is that this only shows the containment triples of the derived resources, if there are standard resources also in this container those will not be shown any more.

Only `ldp:contains` triples are shown, no `rdf:type` or iana media type triples, but it is probably feasible to also add those as the type is determined by the URL, and for the media type we can always take turtle as derived resources are all RDF.

### CODE REVIEW

**Comment by phochste** [comment]
For the resource http://localhost:3000/dummy.txt I get an server error.

```
InternalServerError: There was a problem acquiring the filter to generate the derived resource: 
    at SparqlFilterHandler.handle (/Users/hochsten/github.com/SolidLabResearch/derived-resources-component/dist/SparqlFilterHandler.js:29:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MetadataDerivationManager.deriveResource (/Users/hochsten/github.com/SolidLabResearch/derived-resources-component/dist/MetadataDerivationManager.js:112:24)
    at async RepresentationConvertingStore.getRepresentation (/Users/hochsten/github.com/SolidLabResearch/derived-resources-component/node_modules/@solid/community-server/dist/storage/RepresentationConvertingStore.js:35:32)
    at async BinarySliceResourceStore.getRepresentation (/Users/hochsten/github.com/SolidLabResearch/derived-resources-component/node_modules/@solid/community-server/dist/storage/BinarySliceResourceStore.js:25:24)
    at async GetOperationHandler.handle (/Users/hochsten/github.com/SolidLabResearch/derived-resources-component/node_modules/@solid/community-server/dist/http/ldp/GetOperationHandler.js:26:22)
    at async WacAllowHttpHandler.handle (/Users/hochsten/github.com/SolidLabResearch/derived-resources-component/node_modules/@solid/community-server/dist/server/WacAllowHttpHandler.js:36:24)
    at async ParsingHttpHandler.handleRequest (/Users/hochsten/github.com/SolidLabResearch/derived-resources-component/node_modules/@solid/community-server/dist/server/ParsingHttpHandler.js:44:24)
    at async ParsingHttpHandler.handle (/Users/hochsten/github.com/SolidLabResearch/derived-resources-component/node_modules/@solid/community-server/dist/server/ParsingHttpHandler.js:30:22)
    at async SequenceHandler.handle (/Users/hochsten/github.com/SolidLabResearch/derived-resources-component/node_modules/@solid/community-server/dist/util/handlers/SequenceHandler.js:28:26)

```

**Comment by phochste** [comment]
The two container examples are working, but the reason why with using a `.meta` is quite funky: we can select our own derived resources (!). Maybe in  the `README.md` in the Selector second a few words can be added. To explain also this usage pattern .

**Review by termontwouter — COMMENTED** [review]
Good work, everything looks a bit more polished now as well. 

I'm not quite convinced by how templated IRI's are mentioned as "contained" in a container, though. A UTF-8 reading of `<> <http://www.w3.org/ns/ldp#contains> <{var}>` on `http://localhost:3000/`, would be that there exists a (single) resource identified by `http://localhost:3000/{var}` that is contained in `http://localhost:3000/`. This is also what the browser understands when you follow the link on the graphical representation of the container's index: it directs to `http://localhost:3000/%7Bvar%7D`, which does not exist of course.

Could we consider an alternative approach in the direction of: 
```
<> <http://www.w3.org/ns/ldp#contains> [
    a :TemplatedResource ; 
    :path [ 
        :segments ( "staticPart", _:dynamicPart ) ; 
        :query ( "queryParam" ) 
    ]
] .
```
which would represent `<staticPart/{dynamicPart}{?queryParam}>`?

Semantically, this would make more sense i.m.o., and we could then adapt the graphical interface to parse those in a useful explanation.

**Comment by joachimvh** [comment]
> I'm not quite convinced by how templated IRI's are mentioned as "contained" in a container

I agree that those look weird, hadn't yet thought about what to do with those.

> Could we consider an alternative approach in the direction of

I'll have a look. This is going to drastically complicate the SPARQL query that generates those though 😅.

Problem is that you then expose that these are not "standard" resources, and the `ldp:contains` triple is no longer what is expected. For some cases with a fixed set of options it might be possible to instead have it so all the available options are generated instead of exposing the templated endpoint.

**Comment by termontwouter** [comment]
> Problem is that you then expose that these are not "standard" resources, and the `ldp:contains` triple is no longer what is expected. 

But the same goes for the (non-existing) templated URI as it is implemented now. I think it is better, in the case of templated resources, to provide a format that a machine can actually detect and use to generate URI's for such resources from the template.

Another alternatives, in between the previous proposals, might be to still use the template as object:
- as a string instead of a node (then it is detectable and parseable according to URI Templates syntax);
- as a node (like any other containment triple) but with an extra triple characterizing the node as a templated resource (then derived-resources-aware clients can detect that the URI is not just to be followed) (I don't like the semantics of this though) ;
- as a node linked to the container with another predicate `<> ldpext:templatedContains "{var}"` (plus maybe concrete containment triples if we can generate them).

**Comment by joachimvh** [comment]
I'm currently looking at having something like `<> ldp:contains [ derived:templateUrl "http://localhost/template/{var}" ]`. 

Main problem now is that this requires a different a different SPARQL query to generate, and there is no way to merge CONSTRUCT results in a single query. So to allow both these and other resources in the same container we will need to support multiple filters to generate a single resource. Or change it so a single filter resource can contain multiple queries.

**Comment by joachimvh** [comment]
Going to merge this PR to have the new structure in the main repo and open an issue for the extra suggested behaviour above.

**Pull request merged**
